// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: project.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :execresult
INSERT INTO projects 
(name, description, start_date) 
VALUES ($1, $2, $3)
`

type CreateProjectParams struct {
	Name        string             `json:"name"`
	Description string             `json:"description"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createProject, arg.Name, arg.Description, arg.StartDate)
}
